const r = addNode()
const a = addNode()
const b = addNode()
const c = addNode()
addEdge(r,a)
addEdge(r,b)
addEdge(r,c)
setChildren(r, [b,a,c])
setChildren(r, [c,a,b])
setChildren(r, [b, a])
setChildren(a, [r,b,c])
